### PR TITLE
Darker Variant for the DTM 16

### PR DESCRIPTION
**Pull request by NextdoorPsycho**
This uses your base DTM-16 as a default, so it updates with it.
Just ads a DARKER dark mode for those of us like me that just want things to be a smidgen darker

image
image

### CODE REVIEW

**Comment by XYZenix** [comment]
technically there's already a darker variant but it's only accessible when using the amoled dark experiment
i'll add a method of activating it through a variable in the scss file, but i'm not really planning on having individual `.theme.css` files for those kinds of things cuz they're more of a pain to update/fix

**Comment by NextdoorPsycho** [comment]
Well you cant access AMoled unless you are a Developer (or have the developer tag) and its only persistent until restart

**Comment by XYZenix** [comment]
yeah.. iadded a variable to control forced amoled dark mode after you submitted this pull request, i hope this works well enough
https://github.com/XYZenix/XYZenixThemes/blob/1814b24480bf7bd09ca25293844b0e8a8b3a989d/DTM-16-V5/DTM-16.scss#L37

**Comment by NextdoorPsycho** [comment]
how would i manage to enable this?

**Comment by XYZenix** [comment]
you take the scss file there, change the `false` on that line to `true` and then you compile it
there are some online scss compilers, you could easily find one by searching for it
if you use an online scss compiler, you just copy all the contents of the scss file into the compiler and take the output as a .theme.css

**Comment by NextdoorPsycho** [comment]
that seems like a non-updating system, but ill see what I can do. Thanks for the help. :)

**Pull request closed without merging**
